[package]
name = "alphoko"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.1" }
egui_extras = { version = "0.31.1", features = ["default", "all_loaders"] }
rfd = { version = "0.15.3" }
